name = "zmail"
main = "worker/src/index.ts"

# 打包配置
minify = true # 生产环境压缩代码
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-01"

# 启用 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "zmail"
database_id = "987e6b1a-946a-4cba-84fc-23c4c31d72d6"  # 需要替换为您的实际数据库 ID

# 配置邮件处理
[triggers]
crons = ["0 * * * *"]  # 每小时运行一次清理任务

[assets]
binding = "ASSETS"
directory = "frontend/dist"
not_found_handling = "single-page-application"

# 默认开启日志，方便调试
[observability]
enabled = false
head_sampling_rate = 1 # optional. default = 1.
